(define (make-account balance password)
  (let ((times 0))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch passwd m)
      (if (eq? passwd password)
	  (cond ((eq? m 'withdraw) withdraw)
		((eq? m 'deposit) deposit)
		(else (error "Unknown request -- MAKE-ACCOUNT"
			     m)))
	  (lambda (arg)
	    (set! times (+ times 1))
	    (if (>= times 7)
		"Call procedure call-the-cops"
		"Incorrect password"))))
    dispatch))